apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tech-challenge-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    
    # --- ADICIONE ESTA LINHA ---
    # Isso cria a Tag "Project=TechChallenge" no ALB l√° no console da AWS
    alb.ingress.kubernetes.io/tags: Project=TechChallenge
    # ---------------------------

spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tech-challenge-service
                port:
                  number: 80